mecusto/basket/urls.py
from django.conf.urls import patterns, url
from django.utils.translation import ugettext_lazy as _

urlpatterns = patterns('basket.views',
   url(r'^$', 'basket_page', name='basket-page'),
   url(_(r'^/order$'), 'order_page', name='order-page'),
   url(_(r'^/success$'), 'success_page', name='success-page'),
)

mecusto/choco/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('choco.views',
   url(r'^$', 'index_page', name='index-page'),
   url(r'^/(?P<slug>[\w\-]+)$', 'constructor_page', name='constructor-page'),
   url(r'^/r/(?P<pk>[\w\-]+)$', 'redirect_to_constructor', name='redirect-to-constructor'),
)

mecusto/mecusto/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _

from .admin import mecusto_admin
from .utils.i18n.urls import i18n_patterns


api_v1_patterns = patterns('',
    url(r'^/basket', include('basket.api.urls', namespace='basket')),
    url(r'^/common', include('common.api.urls', namespace='common')),
)

urlpatterns = patterns('common.views',
    url(r'^$', 'root_page', name='root-page'),
    url(r'^set-lang$', 'set_language', name='set-language'),
    url(r'^api/v1', include(api_v1_patterns, namespace='api-v1')),
)

# add slash. before url regex to separate it from language code
# only in these patterns
urlpatterns += i18n_patterns('',
    url(r'^$', 'common.views.index_page', name='index-page'),
    url(_(r'^/chocolate'), include('choco.urls', namespace='choco')),
    url(_(r'^/coffee'), include('coffee.urls', namespace='coffee')),
    url(_(r'^/muesli'), include('muesli.urls', namespace='muesli')),
    url(_(r'^/macarons'), include('macarons.urls', namespace='macarons')),
    url(_(r'^/cake'), include('cakes.urls', namespace='cakes')),
    url(_(r'^/basket'), include('basket.urls', namespace='basket')),
    url(r'', include('flatpages.urls', namespace='flatpages')),
)

# admin urls
urlpatterns += patterns('',
    url(r'^admin/rosetta/', include('rosetta.urls'), name='rosetta'),
    url(r'^admin/', include(mecusto_admin.urls)),
    url(r'^admin/ckeditor/', include('ckeditor.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mecusto/templates/muesli/constructor.html
{% extends 'base.html' %}

{% load staticfiles i18n common_tags %}

{% block js_params %}
	<script type="application/javascript">var pageType = "muesli-constructor", maxIngredientsMessage = '{% trans 'Lubatud maksimaalselt 3 lisandit!' %}',maxIngredientsInProduct = '{% trans 'Maximum ingredients in one product reached. It can be less or equal to' %}';</script>
{% endblock %}

{% block page-class %}class="muesli-page"{% endblock %}

{% block menu %}{% include 'includes/menu.html' with muesli_active=True %}{% endblock %}

{% block html_includes %}{{ block.super }}{% include 'includes/bought-popup.html' with back_url='muesli:index-page' %}{% endblock %}

{% block content %}
	<div class="sidebar">
		<div class="panel">
			<div class="product-face clear" data-base-id="{{ muesli.id }}" data-image="{{ muesli.image.url }}" data-title="{{ muesli.title }}" data-price="{{ muesli.price|to_float }}" data-weight="{{ muesli.weight|to_float }}" data-energy="{{ muesli.energy_value }}" data-fats="{{ muesli.fats }}"
			     data-carbohydrates="{{ chocolate.carbohydrates }}">
				<p>{{ muesli.title|capfirst }}</p>
				<span>500 g</span>
			</div>
			<p>{% trans 'Lisandid' %}:<a class="start-again" href="{% url 'muesli:index-page' %}"><span>X </span>{% trans 'Alustan uuesti' %}</a></p>
			<div class="constructor clear">
				<div></div>
				<div></div>
				<div></div>
				<div></div>
				<div></div>
			</div>
			<div class="price-block">
				<div class="clear">
					<p>{% trans 'Kokku' %}: <span>9.40</span><em>€</em></p>
				</div>
				<a class="btn large to-basket" href="#">{% trans 'Ostukorvi' %}</a>
				<div class="energy">
					<b>{% trans '100g müsli' %}:</b>
					<p>{% trans 'energy value'|capfirst %}: <span>400</span>{% trans 'kcl' %}</p>
					<p>{% trans 'carbohydrates'|capfirst %}: <span>50</span>{% trans 'g' %}</p>
					<p>{% trans 'fats'|capfirst %}: <span>30</span>{% trans 'g' %}</p>
					{#					<p><span>50</span>% GDA</p>#}
				</div>
			</div>
		</div>
	</div>
	<div class="content">
		<div class="breadcrumbs product-index assembly clear">
			<div><a class="help-type" href="{% url 'muesli:index-page' %}">1. {% trans 'Tüüp ja kogus' %}</a></div>
			<div><a class="help-ingredients active">2. {% trans 'Lisandid' %}</a></div>
			<div><a class="help-delivery">3. {% trans 'Ostukorv' %}</a></div>
		</div>
		<div class="notification">
			{% for notification in notifications %}
				<div class="yellow"{% if forloop.counter > 1 %} style="display: none;"{% endif %}>
					<i class="close"></i>
					<p>{{ notification.message|capfirst }}</p>
				</div>
			{% endfor %}
		</div>
		<div class="product-tabs">
			<div class="tabs">
				<ul>
					{% for group in groups %}
						<li><a href="#muesli-{{ forloop.counter }}">{{ group.title|capfirst }}</a></li>
					{% endfor %}
				</ul>
				{% for group in groups %}
					<div id="muesli-{{ forloop.counter }}">
						<ul class="list-product ingredients clear">
							{% for ingredient in group.ingredients %}
								<li data-id="{{ ingredient.id }}" data-title="{{ ingredient.title }}" data-price="{{ ingredient.price|to_float }}" data-weight="{{ ingredient.weight|to_float }}" title="{{ ingredient.description }}" data-imgurl="{{ ingredient.image.url }}" data-energy="{{ ingredient.energy_value }}" data-carbohydrates="{{ ingredient.carbohydrates }}" data-fats="{{ ingredient.fats }}">
									<img src="{{ ingredient.image.url }}" alt="{{ ingredient.title|title }}"/>
									<div class="inform">
										<p>{{ ingredient.title|title }}</p>
										<span><i>{{ ingredient.weight }}</i> {% trans 'grammi' %}</span>
										<span><i>{{ ingredient.price }}</i> {% trans 'senti' %}</span>
									</div>
									<div class="btns">
										<i class="minus">-</i>
										<i class="plus">+</i>
										<span>x1</span>
									</div>
									<i class="add-product">{% trans 'Lisa' %}</i>
								</li>
							{% endfor %}
						</ul>
					</div>
				{% endfor %}
			</div>
		</div>
		<div class="seo-base uncolumned">
			{{ muesli.seo_text|safe }}
		</div>
	</div>
{% endblock %}

mecusto/templates/muesli/index.html
{% extends 'base.html' %}

{% load staticfiles i18n %}

{% block js_params %}
	<script type="application/javascript">var pageType = "choco-index";</script>
{% endblock %}

{% block page-class %}class="muesli-page"{% endblock %}

{% block menu %}{% include 'includes/menu.html' with muesli_active=True %}{% endblock %}

{% block html_includes %}{% include 'includes/bought-popup.html' %}{% endblock %}

{% block content %}
	<div class="top-panel clear">
		<div class="welcome-text left">
			<p>{% trans 'Valmista müsli' %}</p>
			<span>{% trans 'Alusta siit' %}</span>
		</div>
		<div class="breadcrumbs product-index right">
			<div>
				<a class="help-type active">1. {% trans 'Müsli graanol' %}</a>
				<p>{% trans 'Müsli põhi' %}</p>
			</div>
			<div>
				<a class="help-ingredients">2. {% trans 'Lisandid' %}</a>
				<p>{% trans 'Valikus üle 150-ne lisandi' %}</p>
			</div>
			<div>
				<a class="help-delivery">3. {% trans 'Ostukorv' %}</a>
				<p>{% trans 'Maksmine ja kohaletoomine' %}</p>
			</div>
		</div>
	</div>
	<div class="notification">
		<div class="yellow center">
			<i class="close"></i>
			<p>{% trans 'Kolme MÜSLI PAKI TELLIMISEL ON NELJAS TASUTA' %}</p>
		</div>
		{% for notification in notifications %}
		<div class="yellow" style="display: none;">
{#			{% if forloop.counter > 1 %} style="display: none;"{% endif %}>#}
			<i class="close"></i>
			<p>{{ notification.message|capfirst }}</p>
		</div>
		{% endfor %}
	</div>
	<div class="content-product">
		<div class="clear">
			{% for msl in muesli %}
			<div>
				<a href="{% url 'muesli:constructor-page' msl.slug %}" class="img" style="background: url('{{ msl.image.url }}')"></a>
				<p>{{ msl.title|title }}</p>
				<a class="btn arrowed" href="{% url 'muesli:constructor-page' msl.slug %}">{% trans 'Vali' %}</a>
				<span><em>{{ msl.price }}</em> €</span>
			</div>
			{% endfor %}
		</div>
	</div>
{#	{% include 'includes/slider.html' with recommendations=recommendations product_type="muesli" edit_recommendation="muesli:constructor-page" only %}#}
	<div class="seo-base">
		{{ seo_text.text|safe }}
	</div>
{% endblock %}