mecusto/basket/urls.py
from django.conf.urls import patterns, url
from django.utils.translation import ugettext_lazy as _

urlpatterns = patterns('basket.views',
   url(r'^$', 'basket_page', name='basket-page'),
   url(_(r'^/order$'), 'order_page', name='order-page'),
   url(_(r'^/success$'), 'success_page', name='success-page'),
)

mecusto/choco/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('choco.views',
   url(r'^$', 'index_page', name='index-page'),
   url(r'^/(?P<slug>[\w\-]+)$', 'constructor_page', name='constructor-page'),
   url(r'^/r/(?P<pk>[\w\-]+)$', 'redirect_to_constructor', name='redirect-to-constructor'),
)

mecusto/mecusto/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _

from .admin import mecusto_admin
from .utils.i18n.urls import i18n_patterns


api_v1_patterns = patterns('',
    url(r'^/basket', include('basket.api.urls', namespace='basket')),
    url(r'^/common', include('common.api.urls', namespace='common')),
)

urlpatterns = patterns('common.views',
    url(r'^$', 'root_page', name='root-page'),
    url(r'^set-lang$', 'set_language', name='set-language'),
    url(r'^api/v1', include(api_v1_patterns, namespace='api-v1')),
)

# add slash. before url regex to separate it from language code
# only in these patterns
urlpatterns += i18n_patterns('',
    url(r'^$', 'common.views.index_page', name='index-page'),
    url(_(r'^/chocolate'), include('choco.urls', namespace='choco')),
    url(_(r'^/coffee'), include('coffee.urls', namespace='coffee')),
    url(_(r'^/muesli'), include('muesli.urls', namespace='muesli')),
    url(_(r'^/macarons'), include('macarons.urls', namespace='macarons')),
    url(_(r'^/cake'), include('cakes.urls', namespace='cakes')),
    url(_(r'^/basket'), include('basket.urls', namespace='basket')),
    url(r'', include('flatpages.urls', namespace='flatpages')),
)

# admin urls
urlpatterns += patterns('',
    url(r'^admin/rosetta/', include('rosetta.urls'), name='rosetta'),
    url(r'^admin/', include(mecusto_admin.urls)),
    url(r'^admin/ckeditor/', include('ckeditor.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mecusto/templates/coffee/constructor.html
{% extends 'base.html' %}

{% load staticfiles i18n common_tags %}

{% block js_params %}
    <script type="application/javascript">var pageType = "coffee-constructor", maxIngredientsMessage = '{% trans 'Lubatud maksimaalselt 3 lisandit!' %}',maxIngredientsInProduct = '{% trans 'Maximum ingredients in one product reached. It can be less or equal to' %}';</script>
{% endblock %}

{% block page-class %}class="coffee-page"{% endblock %}

{% block menu %}{% include 'includes/menu.html' with coffee_active=True %}{% endblock %}

{% block html_includes %}{{ block.super }}{% include 'includes/bought-popup.html' with back_url='coffee:index-page' %}{% endblock %}

{% block content %}
    <div class="sidebar">
        <div class="panel">
            <div class="product-face clear" data-base-id="{{ coffee.id }}" data-image="{{ coffee.image.url }}" data-title="{{ coffee.title }}" data-price="{% if request.GET.weight == '300' %}{{ coffee.price_300|to_float }}{% else %}{{ coffee.price_150|to_float }}{% endif %}" data-weight="{% if request.GET.weight == '300' %}300{% else %}150{% endif %}" data-energy="{{ coffee.energy_value }}" data-fats="{{ coffee.fats }}" data-carbohydrates="{{ coffee.carbohydrates }}">
                <p>{{ coffee.title }}</p>
                <span>150 g</span>
            </div>
            <div class="product-img clear">
                <p>{% trans 'Lisad' %}:<br /><a class="start-again" href="{% url 'coffee:index-page' %}"><span>X </span>{% trans 'Alustan uuesti' %}</a></p>
                <div class="img">
                    <img src="{{ coffee.image.url }}" alt="{{ coffee.title }}" />
                </div>
            </div>
            <div class="constructor clear">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
            <div class="price-block">
                <div class="clear">
                    <p>{% trans 'Kokku' %}: <span>15.40</span><em>€</em></p>
                </div>
                <a class="btn large to-basket" href="javascript:void(0);">{% trans 'Ostukorvi' %}</a>
                <div class="energy">
                    <b>{% trans '100g' %} {{ coffee.title }}:</b>
                    <p>{% trans 'energy value'|capfirst %}: <span>400</span>{% trans 'kcl' %}</p>
                    <p>{% trans 'carbohydrates'|capfirst %}: <span>50</span>{% trans 'g' %}</p>
                    <p>{% trans 'fats'|capfirst %}: <span>30</span>{% trans 'g' %}</p>
                    {#					<p><span>50</span>% GDA</p>        #}
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="breadcrumbs product-index assembly clear">
            <div><a class="help-type" href="{% url 'coffee:index-page' %}">1. {% trans 'Kohvi tugevus' %}</a></div>
            <div><a class="help-ingredients active">2. {% trans 'Maitsed' %}</a></div>
            <div><a class="help-delivery">3. {% trans 'Ostukorv' %}</a></div>
        </div>
        <div class="notification">
            {% for notification in notifications %}
                <div class="yellow"{% if forloop.counter > 1 %} style="display: none;"{% endif %}>
                    <i class="close"></i>
                    <p>{{ notification.message|capfirst }}</p>
                </div>
            {% endfor %}
        </div>
        <div class="product-tabs">
            <div class="tabs">
                <ul>
                {% for group in groups %}
                    <li><a href="#coffee-{{ forloop.counter }}">{{ group.title|capfirst }}</a></li>
                {% endfor %}
                </ul>
                {% for group in groups %}
                    <div id="coffee-{{ forloop.counter }}">
                        <ul class="list-product ingredients clear">
                            {% for ingredient in group.ingredients %}
                                <li data-id="{{ ingredient.id }}" data-title="{{ ingredient.title }}" data-price="{% if request.GET.weight == '300' %}{{ ingredient.price_300|to_float }}{% else %}{{ ingredient.price_150|to_float }}{% endif %}" data-weight="{% if request.GET.weight == '300' %}{{ ingredient.weight_300|to_float }}{% else %}{{ ingredient.weight_150|to_float }}{% endif %}" title="{{ ingredient.description }}" data-imgurl="{{ ingredient.image.url }}" data-energy="{{ ingredient.energy_value }}" data-carbohydrates="{{ ingredient.carbohydrates }}" data-fats="{{ ingredient.fats }}">
                                    <img src="{{ ingredient.image.url }}" alt="{{ ingredient.title|title }}"/>
                                    <div class="inform">
                                        <p>{{ ingredient.title|title }}</p>
                                        <span><i>{% if request.GET.weight == '300' %}{{ ingredient.weight_300 }}{% else %}{{ ingredient.weight_150 }}{% endif %}</i> {% trans 'grammi' %}</span>
                                        <span><i>{% if request.GET.weight == '300' %}{{ ingredient.price_300 }}{% else %}{{ ingredient.price_150 }}{% endif %}</i> {% trans 'senti' %}</span>
                                    </div>
                                    <div class="btns">
                                        <i class="minus">-</i>
                                        <i class="plus">+</i>
                                        <span>x1</span>
                                    </div>
                                    <i class="add-product">{% trans 'Lisa' %}</i>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="seo-base uncolumned">
	        {{ coffee.seo_text|safe }}
        </div>
    </div>
{% endblock %}

mecusto/templates/coffee/index.html
{% extends 'base.html' %}

{% load i18n common_tags %}

{% block js_params %}
    <script type="application/javascript">var pageType = "coffee-index";</script>
{% endblock %}

{% block page-class %}class="coffee-page"{% endblock %}

{% block menu %}{% include 'includes/menu.html' with coffee_active=True %}{% endblock %}

{% block html_includes %}{% include 'includes/bought-popup.html' %}{% endblock %}

{% block content %}
    <div class="top-panel clear">
        <div class="welcome-text left">
            <p>{% trans 'Valmista kohvi' %}</p>
            <span>{% trans 'Alusta siit' %}</span>
        </div>
        <div class="breadcrumbs product-index right">
            <div>
                <a class="help-type active">1. {% trans 'Röst ja kogus' %}</a>
                <p>{% trans '150 või 300 grammi' %}</p>
            </div>
            <div>
                <a class="help-ingredients">2. {% trans 'Lisandid' %}</a>
                <p>{% trans 'Valikus üle 150-ne lisandi' %}</p>
            </div>
            <div>
                <a class="help-delivery" href="#">3. {% trans 'Ostukorv' %}</a>
                <p>{% trans 'Maksmine ja kohaletoomine' %}</p>
            </div>
        </div>
    </div>
    <div class="weight-panel clear">
        <div class="left">
            <p>{% trans 'Vali kogus' %}:</p>
            <ul class="radio left">
                <li>
                    <input id="weight-150" name="weight" type="radio" checked />
                    <label for="weight-150">{% trans '150 grammi' %}</label>
                </li>
                <li>
                    <input id="weight-300" name="weight" type="radio" />
                    <label for="weight-300">{% trans '300 grammi' %}</label>
                </li>
            </ul>
        </div>
        <div class="left">
            <p>{% trans 'Vali oad' %}:</p>
            <ul class="radio left">
                <li>
                    <input id="ground" name="grist" type="radio" checked />
                    <label for="ground">{% trans 'jahvatatud' %}</label>
                </li>
                <li>
                    <input id="beans" name="grist" type="radio" />
                    <label for="beans">{% trans 'ubadena' %}</label>
                </li>
            </ul>
        </div>
    </div>
    <div class="content-product">
        <p>{% trans 'Vali põhi' %}:</p>
        <div class="clear">
            {% for cf in coffee %}
                <div data-150="{{ cf.price_150|to_float }}" data-300="{{ cf.price_300|to_float }}">
                    <a href="{% url 'coffee:constructor-page' cf.slug %}" class="img">
                        <img src="{{ cf.image.url }}" alt="{{ cf.title|safe }}" />
                    </a>
                    <p>{{ cf.title|safe }}</p>
                    <a class="btn arrowed" href="{% url 'coffee:constructor-page' cf.slug %}">{% trans 'Vali' %}</a>
                    <span><em>{{ cf.price_150 }}</em> €</span>
                    <div class="description">
                        <div><img src="{{ cf.small_image.url }}" alt="" /></div>
                        <i>{{ cf.description|safe }}</i>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{#        {% include 'includes/slider.html' with recommendations=recommendations product_type="coffee" edit_recommendation="coffee:constructor-page" only %}#}
    <div class="seo-base">
	    {{ seo_text.text|safe }}
    </div>
{% endblock %}