mecusto/basket/api/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('basket.api.views',
   url(r'^/save-order$', 'save_order_api', name='save-order'),
)

mecusto/basket/urls.py
from django.conf.urls import patterns, url
from django.utils.translation import ugettext_lazy as _

urlpatterns = patterns('basket.views',
   url(r'^$', 'basket_page', name='basket-page'),
   url(_(r'^/order$'), 'order_page', name='order-page'),
   url(_(r'^/success$'), 'success_page', name='success-page'),
)

mecusto/choco/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('choco.views',
   url(r'^$', 'index_page', name='index-page'),
   url(r'^/(?P<slug>[\w\-]+)$', 'constructor_page', name='constructor-page'),
   url(r'^/r/(?P<pk>[\w\-]+)$', 'redirect_to_constructor', name='redirect-to-constructor'),
)

mecusto/mecusto/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _

from .admin import mecusto_admin
from .utils.i18n.urls import i18n_patterns


api_v1_patterns = patterns('',
    url(r'^/basket', include('basket.api.urls', namespace='basket')),
    url(r'^/common', include('common.api.urls', namespace='common')),
)

urlpatterns = patterns('common.views',
    url(r'^$', 'root_page', name='root-page'),
    url(r'^set-lang$', 'set_language', name='set-language'),
    url(r'^api/v1', include(api_v1_patterns, namespace='api-v1')),
)

# add slash. before url regex to separate it from language code
# only in these patterns
urlpatterns += i18n_patterns('',
    url(r'^$', 'common.views.index_page', name='index-page'),
    url(_(r'^/chocolate'), include('choco.urls', namespace='choco')),
    url(_(r'^/coffee'), include('coffee.urls', namespace='coffee')),
    url(_(r'^/muesli'), include('muesli.urls', namespace='muesli')),
    url(_(r'^/macarons'), include('macarons.urls', namespace='macarons')),
    url(_(r'^/cake'), include('cakes.urls', namespace='cakes')),
    url(_(r'^/basket'), include('basket.urls', namespace='basket')),
    url(r'', include('flatpages.urls', namespace='flatpages')),
)

# admin urls
urlpatterns += patterns('',
    url(r'^admin/rosetta/', include('rosetta.urls'), name='rosetta'),
    url(r'^admin/', include(mecusto_admin.urls)),
    url(r'^admin/ckeditor/', include('ckeditor.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mecusto/basket/models.py
from django.core.mail import EmailMultiAlternatives
from django.db import models
from django.template.loader import render_to_string
from django.utils import translation
from hvad.models import TranslatableModel, TranslatedFields
from django.utils.translation import ugettext_lazy as _
from django.conf import settings as mecusto_settings
from itertools import chain

from mecusto.utils.models import PositionMixin
import settings


class Package(PositionMixin, TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(verbose_name=_('title'), max_length=15)
    )
    product = models.CharField(verbose_name=_('product'), max_length=25, choices=(
        (settings.PACKAGE_CHOCOLATE, _(settings.PACKAGE_CHOCOLATE)),
        (settings.PACKAGE_COFFEE, _(settings.PACKAGE_COFFEE)),
        (settings.PACKAGE_MUESLI, _(settings.PACKAGE_MUESLI)),
        (settings.PACKAGE_MACARONS, _(settings.PACKAGE_MACARONS)),
        (settings.PACKAGE_CAKE, _(settings.PACKAGE_CAKE)),
    ))

    class Meta:
        ordering = 'position',
        verbose_name = _('package')
        verbose_name_plural = _('packages')

    def __unicode__(self):
        return self.safe_translation_getter('title', default=getattr(self, 'title'))


class City(PositionMixin, TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(verbose_name=_('title'), max_length=35)
    )
    delivery_price = models.FloatField(verbose_name=_('delivery price'), default=0.0)

    class Meta:
        ordering = 'position',
        verbose_name = _('city')
        verbose_name_plural = _('cities')

    def __unicode__(self):
        return self.safe_translation_getter('title', default=getattr(self, 'title'))


class Order(models.Model):
    original_cost = models.FloatField(
        verbose_name=_('original order cost'), help_text=_('Order cost without discount')
    )
    cost = models.FloatField(verbose_name=_('order cost'), help_text=_('Order cost with discount'))
    delivery_cost = models.FloatField(verbose_name=_('delivery cost'))
    first_name = models.CharField(verbose_name=_('first name'), max_length=75)
    last_name = models.CharField(verbose_name=_('last name'), max_length=75)
    phone = models.CharField(verbose_name=_('phone'), max_length=20)
    email = models.EmailField(verbose_name=_('email'))
    order_date = models.DateTimeField(verbose_name=_('order date'), auto_now_add=True)
    delivery_date = models.DateField(verbose_name=_('delivery date'))
    delivery_time = models.PositiveSmallIntegerField(
        verbose_name=_('delivery time'), choices=settings.ORDER_TIME_RANGE_CHOICES
    )
    city = models.ForeignKey(verbose_name=_('delivery city'), to='City')
    address = models.TextField(verbose_name=_('delivery address'))
    customer_comment = models.TextField(verbose_name=_('client comment'), blank=True, null=True)
    manager_comment = models.TextField(verbose_name=_('manger comment'), blank=True, null=True)
    promo_code = models.CharField(verbose_name=_('promo code'), max_length=50)
    status = models.PositiveSmallIntegerField(verbose_name=_('order status'), choices=(
        (settings.ORDER_STATUS_ACCEPTED, _('order accepted')),
        (settings.ORDER_STATUS_SENT_TO_PRODUCTION, _('order sent to production')),
        (settings.ORDER_STATUS_SENT_TO_CUSTOMER, _('order sent to customer')),
        (settings.ORDER_STATUS_DELIVERED, _('order delivered')),
        (settings.ORDER_STATUS_IGNORED, _('order ignored'))
    ))
    customer_language = models.CharField(
        verbose_name=_('customer language'), max_length=5, choices=mecusto_settings.LANGUAGES
    )
    mail_delivered = models.BooleanField(verbose_name=_('mail is delivered'), default=False)
    payment_method = models.PositiveSmallIntegerField(verbose_name=_('payment method'), choices=(
        (0, _('courier')),
        (1, _('bill')),
        (2, _('online')),
    ))

    def __unicode__(self):
        return unicode(self.id)

    def get_order_items(self):
        return chain(
            self.chocolate_set.all(),
            self.coffee_set.all(),
            self.muesli_set.all(),
            self.macarons_set.all(),
            self.cake_set.all(),
        )

    def get_customer_full_name(self):
        return u'{0} {1}'.format(self.first_name, self.last_name)

    def send_email(self):
        translation.activate(self.customer_language)
        message = render_to_string('mail/order-info.html', {'order': self})
        msg = EmailMultiAlternatives(
            u'MeGusto # %s' % str(self.id), u'', 'info@megusto.ee', [self.email], cc=['info@megusto.ee']
        )
        msg.attach_alternative(message, "text/html")
        delivered = msg.send()
        if delivered:
            self.mail_delivered = True
            self.save()
        return delivered

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')


class OrderItem(models.Model):
    order = models.ForeignKey(verbose_name=_('order'), to='Order')
    quantity = models.PositiveSmallIntegerField(verbose_name=_('quantity'), default=1)
    price = models.FloatField(verbose_name=_('price'), help_text=_(
        'price without discount for %(b_tag_open)squantity%(b_tag_close)s items' % dict(
            b_tag_open='<b>', b_tag_close='</b>'
        )
    ))
    weight = models.FloatField(verbose_name=_('weight'))
    package = models.ForeignKey(verbose_name=_('package'), to='Package')
    label = models.CharField(verbose_name=_('package label'), default='MeGusto', max_length=20)

    def __unicode__(self):
        return unicode(self.id)

    def get_inner_type(self):
        return self.__class__.__name__.lower()

    def get_price_for_single_item(self):
        return self.price / self.quantity

    def get_ingredients(self):
        raise NotImplementedError

    class Meta:
        abstract = True


class Chocolate(OrderItem):
    base = models.ForeignKey(verbose_name=_('chocolate'), to='choco.Chocolate')
    shape = models.PositiveSmallIntegerField(verbose_name=_('shape type'), choices=(
        (settings.SHAPE_NONE, _('no shape')),
        (settings.SHAPE_HEART, _('heart')),
        (settings.SHAPE_BOX, _('box')),
        (settings.SHAPE_STAR, _('star')),
    ))
    shape_label = models.CharField(verbose_name=_('shape label'), max_length=70, blank=True, null=True)

    def get_ingredients(self):
        return self.chocolateingredient_set.only('ingredient')

    class Meta:
        verbose_name = _('Ordered chocolate')
        verbose_name_plural = _('Ordered chocolates')


class ChocolateIngredient(models.Model):
    item = models.ForeignKey(verbose_name=_('chocolate'), to='Chocolate')
    ingredient = models.ForeignKey(verbose_name=_('ingredient'), to='choco.ChocolateIngredient')
    quantity = models.PositiveSmallIntegerField(
        verbose_name=_('quantity'), default=1, choices=settings.INGREDIENTS_QUANTITY_CHOICES_3
    )

    class Meta:
        verbose_name = _('Ordered chocolate ingredient')
        verbose_name_plural = _('Ordered chocolate ingredient')


class Coffee(OrderItem):
    base = models.ForeignKey(verbose_name=_('coffee'), to='coffee.Coffee')
    grist = models.PositiveSmallIntegerField(verbose_name=_('grist'), default=settings.COFFEE_GRIST_GROUND, choices=(
        (settings.COFFEE_GRIST_GROUND, _('ground')),
        (settings.COFFEE_GRIST_BEANS, _('beans')),
    ))

    def get_ingredients(self):
        return self.coffeeingredient_set.only('ingredient')

    class Meta:
        verbose_name = _('Ordered coffee')
        verbose_name_plural = _('Ordered coffee')


class CoffeeIngredient(models.Model):
    item = models.ForeignKey(verbose_name=_('coffee'), to='Coffee')
    ingredient = models.ForeignKey(verbose_name=_('ingredient'), to='coffee.CoffeeIngredient')
    quantity = models.PositiveSmallIntegerField(
        verbose_name=_('quantity'), default=1, choices=settings.INGREDIENTS_QUANTITY_CHOICES_3
    )

    class Meta:
        verbose_name = _('Ordered coffee ingredient')
        verbose_name_plural = _('Ordered coffee ingredient')


class Muesli(OrderItem):
    base = models.ForeignKey(verbose_name=_('muesli'), to='muesli.Muesli')

    def get_ingredients(self):
        return self.muesliingredient_set.only('ingredient')

    class Meta:
        verbose_name = _('Ordered muesli')
        verbose_name_plural = _('Ordered muesli')


class MuesliIngredient(models.Model):
    item = models.ForeignKey(verbose_name=_('muesli'), to='Muesli')
    ingredient = models.ForeignKey(verbose_name=_('ingredient'), to='muesli.MuesliIngredient')
    quantity = models.PositiveSmallIntegerField(
        verbose_name=_('quantity'), default=1, choices=settings.INGREDIENTS_QUANTITY_CHOICES_3
    )

    class Meta:
        verbose_name = _('Ordered muesli ingredient')
        verbose_name_plural = _('Ordered muesli ingredient')


class Macarons(OrderItem):

    def get_ingredients(self):
        return self.macaronsingredient_set.only('ingredient')

    class Meta:
        verbose_name = _('Ordered macarons')
        verbose_name_plural = _('Ordered macarons')


class MacaronsIngredient(models.Model):
    item = models.ForeignKey(verbose_name=_('macarons'), to='Macarons')
    ingredient = models.ForeignKey(verbose_name=_('ingredient'), to='macarons.Macarons')
    quantity = models.PositiveSmallIntegerField(
        verbose_name=_('quantity'), default=1, choices=settings.INGREDIENTS_QUANTITY_CHOICES_7
    )

    class Meta:
        verbose_name = _('Ordered macarons ingredient')
        verbose_name_plural = _('Ordered macarons ingredient')


class Cake(OrderItem):
    base = models.ForeignKey(verbose_name=_('cake'), to='cakes.Cake')
    shape = models.PositiveSmallIntegerField(verbose_name=_('shape type'), choices=(
        (settings.SHAPE_NONE, _('no shape')),
        (settings.SHAPE_HEART, _('heart')),
        (settings.SHAPE_BOX, _('box')),
        (settings.SHAPE_STAR, _('star')),
    ))

mecusto/basket/forms.py
#! -*- coding: utf-8 -*-
from django import forms


class OrderValidationForm(forms.Form):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    phone = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)
    date = forms.CharField(required=True)
    time = forms.IntegerField(required=True)
    city = forms.CharField(required=True)
    address = forms.CharField(required=True, widget=forms.Textarea)
    comment = forms.CharField(required=False, widget=forms.Textarea)
    payment_method = forms.IntegerField(required=False)
    newsletter = forms.BooleanField(required=False)
    promo_code = forms.CharField(required=False)

    class Meta:
        exclude = ()

mecusto/basket/views.py
from django.http.response import Http404
from django.views.generic import TemplateView

from basket.models import Package, City, Order
import settings as basket_settings
from datetime import datetime


class BasketPage(TemplateView):
    template_name = 'basket/basket.html'

    def get_context_data(self, **kwargs):
        kwargs.update(**self.get_packages())
        return kwargs

    @staticmethod
    def get_packages():
        all_packages = list(Package.objects.language().values('id', 'title', 'product'))
        return {
            '%s_packages' % basket_settings.PACKAGE_CHOCOLATE: [
                i for i in all_packages if i['product'] == basket_settings.PACKAGE_CHOCOLATE
            ],
            '%s_packages' % basket_settings.PACKAGE_COFFEE: [
                i for i in all_packages if i['product'] == basket_settings.PACKAGE_COFFEE
            ],
            '%s_packages' % basket_settings.PACKAGE_MUESLI: [
                i for i in all_packages if i['product'] == basket_settings.PACKAGE_MUESLI
            ],
            '%s_packages' % basket_settings.PACKAGE_CAKE: [
                i for i in all_packages if i['product'] == basket_settings.PACKAGE_CAKE
            ],
            '%s_packages' % basket_settings.PACKAGE_MACARONS: [
                i for i in all_packages if i['product'] == basket_settings.PACKAGE_MACARONS
            ]
        }


class OrderPage(TemplateView):
    template_name = 'basket/order.html'

    def get(self, request, *args, **kwargs):
        return super(OrderPage, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs.update({
            'time_range': basket_settings.ORDER_TIME_RANGE_CHOICES,
            'cities': City.objects.all(),
            'min_date': '+1d' if datetime.now().hour < 11 else '+2d'
        })
        return super(OrderPage, self).get_context_data(**kwargs)


class SuccessPage(TemplateView):
    template_name = 'basket/success.html'

    def get(self, request, *args, **kwargs):
        if 'order_id' not in self.request.session:
            raise Http404()
        try:
            self.order = Order.objects.get(id=self.request.session['order_id'])
        except Order.DoesNotExist:
            raise Http404()
        del self.request.session['order_id']
        self.request.session.modified = True
        return super(SuccessPage, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs.update({'order': self.order})
        return kwargs

basket_page = BasketPage.as_view()
order_page = OrderPage.as_view()
success_page = SuccessPage.as_view()

mecusto/templates/basket/basket.html
{% extends 'base.html' %}

{% load i18n solo_tags %}
{% get_solo 'common.AvailabilityConfiguration' as availability_configuration %}

{% block js_params %}
	<script type="application/javascript">var pageType = "basket-index",lisandid = '{% trans 'Lisandid' %}',vali = '{% trans 'Vali teema pakend' %}',muuda = '{% trans 'Muuda' %}',lisaPackendile = '{% trans 'Lisa pakendile sõnum' %}';</script>
{% endblock %}

{% block page-class %}class="basket-page empty"{% endblock %}

{% block menu %}{% include 'includes/menu.html' with basket_active=True %}{% endblock %}

{% block content %}
	<div class="top-panel clear">
		<div class="welcome-text left">
			<p>{% trans 'Ostukorv' %}</p>
		</div>
		<div class="breadcrumbs product-index right">
			<div>
				<a class="help-overview active">1. {% trans 'Ülevaade' %}</a>
			</div>
			<div>
				<a class="help-validation">2. {% trans 'Kinnitamine' %}</a>
			</div>
			<div>
				<a class="help-pay">3. {% trans 'Maksmine' %}</a>
			</div>
		</div>
	</div>
	<div id="cart-product" class="fluid-content clear"></div>
	<div id="templates" style="display: none;">
		<div id="chocolate-package">
			<div class="package clear" id="">
				<p class="title">{% trans 'Vali teema pakend' %}:</p>
				<select name="speed" class="package-select">
					{% for package in chocolate_packages %}
						<option value="{{ package.id }}">{{ package.title|upper }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<div id="coffee-package">
			<div class="package clear">
				<p class="title">{% trans 'Vali teema pakend' %}:</p>
				<select name="speed" class="package-select">
					{% for package in coffee_packages %}
						<option value="{{ package.id }}">{{ package.title|upper }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<div id="muesli-package">
			<div class="package clear">
				<p class="title">{% trans 'Vali teema pakend' %}:</p>
				<select name="speed" class="package-select">
					{% for package in muesli_packages %}
						<option value="{{ package.id }}">{{ package.title|upper }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<div id="cake-package">
			<div class="package clear">
				<p class="title">{% trans 'Vali teema pakend' %}:</p>
				<select name="speed" class="package-select">
					{% for package in cake_packages %}
						<option value="{{ package.id }}">{{ package.title|upper }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<div id="macarons-package">
			<div class="package clear">
				<p class="title">{% trans 'Vali teema pakend' %}:</p>
				<select name="speed" class="package-select">
					{% for package in macarons_packages %}
						<option value="{{ package.id }}">{{ package.title|upper }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<div class="empty-basket">
			<h2>{% trans 'Ostukorv on veel tühi!' %}</h2>
			<p class="decor-arrow">{% trans 'Valmista ise ja lisa ostukorvi' %}</p>
			<div class="wrapper">
				{% if availability_configuration.chocolate_is_available %}<a href="{% url 'choco:index-page' %}" class="btn chocolate">{% trans 'Šokolaadid' %}</a>{% endif %}
				{% if availability_configuration.muesli_is_available %}<a href="{% url 'muesli:index-page' %}" class="btn muesli">{% trans 'Müsli' %}</a>{% endif %}
				{% if availability_configuration.macarons_is_available %}<a href="{% url 'macarons:constructor-page' %}" class="btn macarons">{% trans 'Makroonid' %}</a>{% endif %}
				{% if availability_configuration.cakes_is_available %}<a href="{% url 'cakes:index-page' %}" class="btn cake">{% trans 'Tordid' %}</a>{% endif %}
				{% if availability_configuration.coffee_is_available %}<a href="{% url 'coffee:index-page' %}" class="btn coffee">{% trans 'Kohvi' %}</a>{% endif %}
			</div>
		</div>
		<div class="basket-total">
			<div class="cart-total-price right">
				<p class="price">{% trans 'Kokku' %}: <span>0</span>€</p>
				<p class="weight">{% trans 'Kaal' %}: <span>0</span> {% trans 'kg' %}</p>
				<a class="btn large to-basket" href="{% url 'basket:order-page' %}">{% trans 'Edasi' %}</a>
				<a class="link" href="{% url 'index-page' %}">{% trans 'Tagasi poodi' %}</a>
			</div>
		</div>
		<div class="shape">
			<div class="clear shape-preview">
				<p class="title">{% trans 'Kuju pealdised' %}:</p>
				<i class="shape-preview-icon">&nbsp;</i>
				<a href="" class="left">{% trans 'Muuda' %}</a>
			</div>
		</div>
		<div class="change-package-text">
			<div class="change-package-title">
				<a href="javascript:void(0);" class="close"></a>
				<div class="wrapper">
					<input type="text" placeholder="{% trans '“MeGusto” (kuni 20 tähemärki)' %}" maxlength="20">
					<button>&nbsp;</button>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

mecusto/templates/basket/success.html
{% extends 'base.html' %}

{% load static i18n %}

{% block page-class %}class="basket-page success"{% endblock %}

{% block js_params %}
	<script type="application/javascript">var pageType = "basket-success";</script>
{% endblock %}

{% block menu %}{% include 'includes/menu.html' with basket_active=True %}{% endblock %}

{% block content %}
	<div class="top-panel clear">
		<div class="welcome-text left">
			<p>{% trans 'Ostukorv' %}</p>
		</div>
		<div class="breadcrumbs product-index right">
			<div><a class="help-overview">1. {% trans 'Ülevaade' %}</a></div>
			<div><a class="help-validation">2. {% trans 'Kinnitamine' %}</a></div>
			<div><a class="help-pay active">3. {% trans 'Maksmine' %}</a></div>
		</div>
	</div>
	<div>
		<div class="fluid-content">
			<div class="thanks">
				<p class="vt-center"><span>{% trans 'Täname' %}!</span></p>
				<p class="vt-center sec">
                    <span>
                        {% trans 'Arve saatsime sinu e-mailile' %} <i>{{ order.email|lower }}</i>
                        <br/>
                        {% trans 'Sinu tellimus juba täitmisel' %} :)
                    </span>
				</p>
			</div>
			<div class="user-info">
				<div class="body">
					<p class="title">{% trans 'Tellija andmed' %}:</p>
					<p>{% trans 'Tellimuse number' %}: <span>{{ order.id }}</span></p>
					<p>{% trans 'Kuupäev' %}: <span>{{ order.order_date|date:'d.m.Y' }}</span></p>
					<p>{% trans 'Telefoni number' %}: <span>{{ order.phone }}</span></p>
					<p>{% trans 'Kohaletoomise aeg' %}: <span>{{ order.delivery_date|date:'d E' }}, {{ order.get_delivery_time_display }}</span></p>
					<p>Email: <span>{{ order.email|lower }}</span></p>
					<p>{% trans 'Kohaletoomise aadress' %}: <span>{{ order.address }}</span></p>
					<p>{% trans 'Nimi ja perekonnanimi' %}: <span>{{ order.get_customer_full_name|title }}</span></p>
					{% if order.customer_comment %}<p>{% trans 'Teie kommentaarid' %}: <br/><span>{{ order.customer_comment }}</span></p>{% endif %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}