mecusto/basket/urls.py
from django.conf.urls import patterns, url
from django.utils.translation import ugettext_lazy as _

urlpatterns = patterns('basket.views',
   url(r'^$', 'basket_page', name='basket-page'),
   url(_(r'^/order$'), 'order_page', name='order-page'),
   url(_(r'^/success$'), 'success_page', name='success-page'),
)

mecusto/choco/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('choco.views',
   url(r'^$', 'index_page', name='index-page'),
   url(r'^/(?P<slug>[\w\-]+)$', 'constructor_page', name='constructor-page'),
   url(r'^/r/(?P<pk>[\w\-]+)$', 'redirect_to_constructor', name='redirect-to-constructor'),
)

mecusto/mecusto/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _

from .admin import mecusto_admin
from .utils.i18n.urls import i18n_patterns


api_v1_patterns = patterns('',
    url(r'^/basket', include('basket.api.urls', namespace='basket')),
    url(r'^/common', include('common.api.urls', namespace='common')),
)

urlpatterns = patterns('common.views',
    url(r'^$', 'root_page', name='root-page'),
    url(r'^set-lang$', 'set_language', name='set-language'),
    url(r'^api/v1', include(api_v1_patterns, namespace='api-v1')),
)

# add slash. before url regex to separate it from language code
# only in these patterns
urlpatterns += i18n_patterns('',
    url(r'^$', 'common.views.index_page', name='index-page'),
    url(_(r'^/chocolate'), include('choco.urls', namespace='choco')),
    url(_(r'^/coffee'), include('coffee.urls', namespace='coffee')),
    url(_(r'^/muesli'), include('muesli.urls', namespace='muesli')),
    url(_(r'^/macarons'), include('macarons.urls', namespace='macarons')),
    url(_(r'^/cake'), include('cakes.urls', namespace='cakes')),
    url(_(r'^/basket'), include('basket.urls', namespace='basket')),
    url(r'', include('flatpages.urls', namespace='flatpages')),
)

# admin urls
urlpatterns += patterns('',
    url(r'^admin/rosetta/', include('rosetta.urls'), name='rosetta'),
    url(r'^admin/', include(mecusto_admin.urls)),
    url(r'^admin/ckeditor/', include('ckeditor.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mecusto/templates/includes/basket-popup.html
{% load i18n %}
<div class="cart-popup">
	<div class="wrapper">
		<p>{% trans 'Ostukorvis' %}:</p>
		<div class="goods"></div>
		<a href="{% url 'basket:basket-page' %}" class="to-cart">{% trans 'vormista ost' %}</a>
	</div>
</div>

mecusto/templates/includes/bought-popup.html
{% load i18n %}
<div class="to-cart-popup">
	<div class="wrapper">
		<div class="inner">
			<p>{% trans 'TÄNAME, LISATUD OSTUKORVI' %}</p>
			<div class="arrow-block">
				<a class="btn arrowed left" href="{% if back_url %}{% url back_url %}{% else %}javascript:void(0);{% endif %}">{% trans 'Valin veel' %}</a>
				<a class="btn arrowed" href="{% url 'basket:basket-page' %}">{% trans 'Maksma' %}</a>
			</div>
		</div>
	</div>
</div>

mecusto/templates/includes/menu.html
{% load i18n solo_tags common_tags %}
{% get_solo 'common.AvailabilityConfiguration' as availability_configuration %}
<nav class="clear">
	<ul>
		{% if availability_configuration.chocolate_is_available %}
			<li{% if choco_active %} class="active"{% endif %}>
				<a href="{% url 'choco:index-page' %}" class="choco">{% trans 'Šokolaadid' %}</a>
				<div class="popup">
					<ul>
						{% for item in choco_menu_items %}
                        <li><a href="{% url 'choco:constructor-page' item.slug %}">{{ item.title|striptags }}</a></li>
                        {% endfor %}
{#						<li><a href="#">{% trans 'Šokolaad pulma' %}</a></li>#}
					</ul>
				</div>
			</li>
		{% endif %}
		{% if availability_configuration.muesli_is_available %}
			<li{% if muesli_active %} class="active"{% endif %}><a href="{% url 'muesli:index-page' %}" class="muesli">{% trans 'Müsli' %}</a></li>
		{% endif %}
		{% if availability_configuration.macarons_is_available %}
			<li{% if macarons_active %} class="active"{% endif %}><a href="{% url 'macarons:constructor-page' %}" class="macarons">{% trans 'Makroonid' %}</a></li>
		{% endif %}
		{% if availability_configuration.cakes_is_available %}
			<li{% if cake_active %} class="active"{% endif %}><a href="{% url 'cakes:index-page' %}" class="cakes">{% trans 'Tordid' %}</a></li>
		{% endif %}
		{% if availability_configuration.coffee_is_available %}
			<li{% if coffee_active %} class="active"{% endif %}>
				<a href="{% url 'coffee:index-page' %}" class="coffee">{% trans 'Kohvi' %}</a>
{#				<div class="popup">#}
{#					<ul>#}
{#						<li><a href="#">{% trans 'Valmis retseptid' %}</a></li>#}
{#						<li><a href="#">{% trans 'Must šokolaad' %}</a></li>#}
{#						<li><a href="#">{% trans 'Valge šokolaad' %}</a></li>#}
{#					</ul>#}
{#				</div>#}
			</li>
		{% endif %}
		{% get_flatpage flatpages pk=2 as about_flatpage %}
		<li>
            <a href="{{ about_flatpage.get_url }}">{{ about_flatpage.title|capfirst }}</a>
            <div class="popup">
                <ul>
                    {% for item in flatpages %}
                    {% if item.id != 8 %}<li><a href="{% url 'flatpages:content-page' item.slug %}">{{ item.title|capfirst }}</a></li>{% endif %}
                    {% endfor %}
                </ul>
            </div>
        </li>
		{% get_flatpage flatpages pk=8 as corp_flatpage %}
		<li><a href="{{ corp_flatpage.get_url }}" class="corp">{{ corp_flatpage.title|capfirst }}</a></li>
	</ul>
</nav>

mecusto/templates/includes/seo-block.html
{% load static i18n solo_tags %}
{% get_solo 'common.IndexPageTabsManagement' as tabs_managment %}
<div class="tabs">
    <ul>
        {% if availability_configuration.chocolate_is_available %}<li><a href="#choco">{% trans 'Šokolaadid' %}</a></li>{% endif %}
        {% if availability_configuration.muesli_is_available %}<li><a href="#muesli">{% trans 'Müsli' %}</a></li>{% endif %}
        {% if availability_configuration.macarons_is_available %}<li><a href="#macarons">{% trans 'Makroonid' %}</a></li>{% endif %}
        {% if availability_configuration.cakes_is_available %}<li><a href="#cakes">{% trans 'Tordid' %}</a></li>{% endif %}
        {% if availability_configuration.coffee_is_available %}<li><a href="#coffee">{% trans 'Kohvi' %}</a></li>{% endif %}
    </ul>
    {% if availability_configuration.chocolate_is_available %}
        <div id="choco">
            <div class="img"><img src="{{ tabs_managment.chocolate_image.url }}" alt="{% trans 'Šokolaadid' %}" /></div>
            <p>{{ tabs_managment.chocolate }}</p>
            <a class="btn" href="{% url 'choco:index-page' %}">{% trans 'Telli kohe' %}</a>
        </div>
    {% endif %}
    {% if availability_configuration.macarons_is_available %}
        <div id="macarons">
            <div class="img"><img src="{{ tabs_managment.macarons_image.url }}" alt="{% trans 'Makroonid' %}" /></div>
            <p>{{ tabs_managment.macarons }}</p>
            <a class="btn" href="{% url 'macarons:constructor-page' %}">{% trans 'Telli kohe' %}</a>
        </div>
    {% endif %}
    {% if availability_configuration.muesli_is_available %}
        <div id="muesli">
            <div class="img"><img src="{{ tabs_managment.muesli_image.url }}" alt="{% trans 'Müsli' %}" /></div>
            <p>{{ tabs_managment.muesli }}</p>
            <a class="btn" href="{% url 'muesli:index-page' %}">{% trans 'Telli kohe' %}</a>
        </div>
    {% endif %}
    {% if availability_configuration.coffee_is_available %}
        <div id="coffee">
            <div class="img"><img src="{{ tabs_managment.coffee_image.url }}" alt="{% trans 'Kohvi' %}" /></div>
            <p>{{ tabs_managment.coffee }}</p>
            <a class="btn" href="{% url 'coffee:index-page' %}">{% trans 'Telli kohe' %}</a>
        </div>
    {% endif %}

    {% if availability_configuration.cakes_is_available %}
        <div id="cakes">
            <div class="img"><img src="{{ tabs_managment.cake_image.url }}" alt="{% trans 'Tordid' %}" /></div>
            <p>{{ tabs_managment.cake }}</p>
            <a class="btn" href="{% url 'cakes:index-page' %}">{% trans 'Telli kohe' %}</a>
        </div>
    {% endif %}
</div>

mecusto/templates/includes/sidebar.html
{% load staticfiles i18n solo_tags %}
<div class="infobar">
	<p class="title">{% trans 'Meist' %}:</p>
	<ul class="info-menu">
		{% for fp in flatpages %}
			{% if fp.id != 8 %}
				<li><a href="{{ fp.get_url }}"{% ifequal flatpage.id fp.id %} class="active" {% endifequal %}>{{ fp.title|capfirst }}</a></li>
			{% endif %}
		{% endfor %}
	</ul>
	<p class="title">{% trans 'Valmista ise' %}:</p>
	<ul class="info-product">
		{% if availability_configuration.coffee_is_available %}
			<li><a class="coffee" href="{% url 'coffee:index-page' %}">{% trans 'Kohvi' %}</a></li>
		{% endif %}
		{% if availability_configuration.muesli_is_available %}
			<li><a class="muesli" href="{% url 'muesli:index-page' %}">{% trans 'Müsli' %}</a></li>
		{% endif %}
		{% if availability_configuration.macarons_is_available %}
			<li><a class="macarons" href="{% url 'macarons:constructor-page' %}">{% trans 'Makroonid' %}</a></li>
		{% endif %}
		{% if availability_configuration.cakes_is_available %}
			<li><a class="cake" href="{% url 'cakes:index-page' %}">{% trans 'Tordid' %}</a></li>
		{% endif %}
		{% if availability_configuration.chocolate_is_available %}
			<li><a class="choco" href="{% url 'choco:index-page' %}">{% trans 'Šokolaadid' %}</a></li>
		{% endif %}
	</ul>
	{#    <a href="javascript:void(0);" class="banner">#}
	{#        <img src="{% static 'img/banners/1.png' %}" alt="" />#}
	{#    </a>#}
</div>

mecusto/templates/includes/slider.html
{% load i18n common_tags %}
<div class="slide-block">
	<p>{% trans 'VALMIS RETSEPTID' %}:</p>
{#  all recipes link #}
	<a href="#">{% trans 'VAATA KÕIKI' %}</a>
	<div class="slider">
		{% for recommendation in recommendations %}
		<div data-base-id="{{ recommendation.base_id }}" data-image="{{ recommendation.image.url }}" data-title="{{ recommendation.base.title }}" data-recommendation-title="{{ recommendation.title }}" data-product-type="{{ product_type }}" data-weight="{{ recommendation.get_weight|to_float }}" data-price="{{ recommendation.get_price|to_float }}" data-ingredients="{{ recommendation.get_ingredients_json }}">
			<div class="img"><img src="{{ recommendation.image.url }}" alt="{{ recommendation.title|title }}"/></div>
			<div class="txt">
				<p>{{ recommendation.title|title }}</p>
				<b>{{ recommendation.sub_title }}</b>
{#				<span>Jelly beans tart tiramisu jelly-o apple pie bear claw marshmallow cotton candy danish. Tart muffin lemon drops gummies soufflé chocolate bar brownie. Jelly beans tiramisu tart... <a href="#">loe edasi</a></span>#}
				<span>{{ recommendation.description|safe }}</span>
				<a class="btn right add-recommendation" href="javascript:void(0);">{% trans 'LISA OSTUKORVI' %}</a>
				<a class="btn black right edit-recommendation" href="{% if edit_recommendation %}{% url edit_recommendation recommendation.base.slug %}{% ifequal recommendation.weight 1 %}?weight=kilogram{% endifequal %}{% else %}{% endif %}">{% trans 'MUUDA KOOSTIST' %}</a>
			</div>
		</div>
		{% endfor %}
	</div>
</div>

mecusto/templates/includes/social.html
<ul class="social">
	<li><a target="_blank" href="http://instagram.com/megustotreats" class="in"></a></li>
	<li><a target="_blank" href="https://www.facebook.com/megusto.ee" class="fb"></a></li>
	<li><a target="_blank" href="https://twitter.com/Megustofactory" class="tw"></a></li>
	<li><a target="_blank" href="https://plus.google.com/u/0/b/100607624118431659227/100607624118431659227/posts" class="gl"></a></li>
    <li><a target="_blank" href="http://vk.com/megustofoodfactory" class="vk"></a></li>
</ul>

mecusto/templates/includes/subscribe-popup.html
{% load i18n %}
<div class="subscribe-popup">
	<div class="wrapper">
		<div class="inner">
			<p>{% trans 'Täname, te olete edukalt registreerunud MeGusto uudiskirjaga' %}</p>
			<div class="arrow-block">
				<i class="btn">{% trans 'Sulge' %}</i>
			</div>
		</div>
	</div>
</div>

mecusto/templates/includes/thanks-popup.html
{% load i18n %}
<div class="thanks-popup" style="display: none">
	<div class="wrapper">
		<div class="inner">
			<p>{% trans 'Täname informatsiooni, võtame Sinuga ühendust' %}!</p>
			<div class="arrow-block">
				<i class="btn">{% trans 'Sulge' %}</i>
			</div>
		</div>
	</div>
</div>